run:
  timeout: 5m
  tests: true
  # Skip version check if needed
  skip-dirs-use-default: true

linters:
  enable:
    - revive      # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - stylecheck  # Replacement for golint, checks Go code style
    - goconst     # Finds repeated strings that could be replaced by a constant
    - misspell    # Finds commonly misspelled English words in comments
    - godot       # Check if comments end in a period
    - gofmt       # Checks whether code was gofmt-ed
    - goimports   # Check import statements are formatted according to the 'goimport' command

linters-settings:
  revive:
    rules:
      # Enforce proper naming conventions including acronyms (catches ApiUrl → APIUrl)
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "API", "URL", "URI", "HTTP", "HTTPS", "JSON", "XML", "HTML", "SQL", "DB", "OS", "UID", "GID", "UUID"] # common initialisms

  stylecheck:
    # ST1003: Names should use MixedCaps or mixedCaps (catches acronym issues like ApiUrl)
    checks: ["all", "-ST1000", "-ST1003"]
    initialisms: ["API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "LHS", "QPS", "RAM", "RHS", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "DB", "OS", "GID"]

  goconst:
    # Minimum length of string constant to check for duplication (catches hardcoded URLs)
    min-len: 3
    # Minimum occurrences count to trigger issue (2 = appears twice or more)
    min-occurrences: 2
    # Ignore test files
    ignore-tests: true

  misspell:
    # Locale can be "US" or "UK" - helps catch French words mixed in comments
    locale: US
    # Ignore words list can be added here if needed
    # ignore-words:
    #   - someword

  godot:
    # Check all top-level comments for proper punctuation
    scope: toplevel
    exclude: []
    capital: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
