version: "2"

run:
  timeout: 5m

linters:
  enable:
    - revive
    - stylecheck
    - goconst
    - misspell
    - gofmt
    - goimports

settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "API", "URL", "URI", "HTTP", "HTTPS", "JSON", "XML", "HTML", "SQL", "DB", "OS", "UID", "GID", "UUID"]
  
  stylecheck:
    checks: ["all", "-ST1000"]
    initialisms: ["API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "LHS", "QPS", "RAM", "RHS", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "DB", "OS", "GID"]
  
  goconst:
    min-len: 3
    min-occurrences: 2
  
  misspell:
    locale: US

