version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
builds:
  - main: main.go
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    binary: geol
    ldflags:
      - "-X 'main.Version={{.Version}}'"
      - "-X 'main.Commit={{.Commit}}'"
      - "-X 'main.Date={{.Date}}'"

archives:
  - # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      geol_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - src: completions/*
      - src: manpages/*

checksum:
  name_template: 'checksums.txt'


sboms:
  - id: geol-source
    artifacts: archive